### ISSUE TITLE
golang.org/x/net/html is obsoleted.

### ISSUE THREAD

**Issue by facat** [microcosm-cc/bluemonday#11]
Your package import golang.org/x/net/html. This url is obsoleted, which leads to

    unrecognized import path "golang.org/x/net/html" 

Maybe you need change it to https://github.com/golang/net

**Comment by shurcooL** [comment]
What makes you believe [`golang.org/x/net/html`](https://godoc.org/golang.org/x/net/html) is obsoleted it? That seems very unlikely, and it does not appear to be so.

**Comment by facat** [comment]
@shurcooL 
Edit1: When I visit golang.org/x/net/html in browser, it's redirected to https://godoc.org/golang.org/x/net/html.

Edit2: This is what I get:

    go get -d -u github.com/microcosm-cc/bluemonday
    package github.com/microcosm-cc/bluemonday
            imports golang.org/x/net/html: unrecognized import path "golang.org/x/net/html"

**Comment by shurcooL** [comment]
@facat, can you do `go version`, what does it print?

**Comment by facat** [comment]
@shurcooL 

    $ go version
    go version go1.4.2 linux/arm

**Comment by shurcooL** [comment]
That's strange, it should work.

Can you try with a fresh (empty) GOPATH workspace and see what happens?

```
$ export GOPATH=/tmp/empty_folder
$ go get -d -u github.com/microcosm-cc/bluemonday
```

**Comment by facat** [comment]
@shurcooL 
Fixed.
golang.org is blocked in my place. I made it through a proxy. Thanks.
