### ISSUE TITLE
douceur entries in go.mod

### ISSUE THREAD

**Issue by udf2457** [microcosm-cc/bluemonday#114]
I noticed your go.mod has the following entries:

```
	github.com/aymerick/douceur v0.2.0 // indirect
	github.com/chris-ramon/douceur v0.2.0
```

Surely this is a bit risky as `chris-ramon/douceur` is currently 14 commits ahead, 2 commits behind `aymerick`.

Continuing to diverge from `aymerick` will mean you will eventually hit some obscure issue that is near impossible to troubleshoot ?

**Comment by buro9** [comment]
Good catch, I've changed the import to the better maintained fork.
