### ISSUE TITLE
Is there a way to allow all URL schemes?

### ISSUE THREAD

**Issue by yardenshoham** [microcosm-cc/bluemonday#174]
Basically something like `AllowURLSchemeWithCustomPolicy` but for all schemes.

References:
- https://github.com/go-gitea/gitea/issues/21146
- https://github.com/go-gitea/gitea/issues/16721

**Comment by buro9** [comment]
Today there isn't.

It would probably require the addition of `AllowURLSchemesRegexp(r regexp)` and then instead of matching a fixed set of strings it would match the regexp. To allow all you'd merely set a regexp to `.*`.

If you wanted to make a working PR with a test for it, I would accept it.

**Comment by yardenshoham** [comment]
- I created #175

**Comment by buro9** [comment]
Thanks, I've been snowed under with a fairly large incident the last few days, but I've just taken a look and this is great so I'll merge now and will cut a release.
