### ISSUE TITLE
Closing anchor and font tags mixed up

### ISSUE THREAD

**Issue by wingedpig** [microcosm-cc/bluemonday#18]
With the following sample program, in the output, the closing anchor tag is missing and in its place is an erroneous closing font tag:

	package main

	import (
		"fmt"

		"github.com/microcosm-cc/bluemonday"
	)

	func main() {
		in := `<font face="Arial">No link here. <a href="http://link.com">link here</a>.</font> Should not be linked here.`
		p := bluemonday.UGCPolicy()
		p.AllowAttrs("color").OnElements("font")
		fmt.Printf("'%s'\n", p.Sanitize(in))
	}

Am I doing something wrong, or is this a bug?

**Comment by manfer** [comment]
bluemonday makes use of [golang package html](golang.org/x/net/html)
> Package html implements an HTML5-compliant tokenizer and parser.

So bluemonday works only with HTML5

Font tag is not a valid HTML5 tag

**Comment by buro9** [comment]
It's not the HTML5 thing, I use the parsing of the golang package to tokenise but it should still output the correct tags.

This appears to be an error related to how empty tags are managed and matched. I'll look at it now.

**Comment by buro9** [comment]
@wingedpig you should find this works now, please test it and get back to me if this is not working for you.

Thanks for reporting it.
