### ISSUE TITLE
skip nested tags by attrs bug

### ISSUE THREAD

**Issue by CMogilko** [microcosm-cc/bluemonday#21]
Example:
```go
p := bluemonday.NewPolicy()
p.AllowElements("tag1", "tag2")
res := p.Sanitize("<tag1><tag2>abc</tag2></tag1><p>test</p>")
fmt.Println(res)
```
Output:
`abc</tag1>test`
Correct output:
`abctest`

**Comment by shurcooL** [comment]
I am confused.

[`AllowElements`](https://godoc.org/github.com/microcosm-cc/bluemonday#Policy.AllowElements) says:

> AllowElements will append HTML elements to the whitelist without applying an attribute policy to those elements (the elements are permitted sans-attributes)

If you're doing `p.AllowElements("tag1", "tag2")`, why are elements `tag1` and `tag2` removed from the output?

Shouldn't correct output be `<tag1><tag2>abc</tag2></tag1>test`?

**Comment by CMogilko** [comment]
@shurcooL 
They are without any attributes and not listed in setOfElementsWithoutAttrs list.
`p.AllowNoAttrs().OnElements("tag1", "tag2")` will do the work.
Standart html tags are listed in setOfElementsWithoutAttrs, so for `p.AllowElements("b")` will work, for `p.AllowElements("tag")` no.

**Comment by shurcooL** [comment]
@buro9, is that intended by design? If so, I think the func name and its documentation are somewhat misleading.

**Comment by buro9** [comment]
That is by design, and there were no docs on that struct property, but I've added docs explaining that and internally renamed the property so that it is clearer.
