### ISSUE TITLE
Custom handlers

### ISSUE THREAD

**Issue by CMogilko** [microcosm-cc/bluemonday#24]
What about adding custom handlers for html elements?
Without it user is forced to parse html second time by himself. Also custom handler allows to use more complicated content-dependent sanitizing.

For example, emails. Emails stored as original, but displayed sanitized and to display embed images it is needed to replace content-id ("cid:url") with real url.
```go
p.SetCustomElementHandler(
	func(token html.Token) bluemonday.HandlerResult {
		for i := range token.Attr {
			// possible image locations
			if token.Attr[i].Key == "src" || token.Attr[i].Key == "background" {
				cid := token.Attr[i].Val // get content-id
				url := GetUrlFromCid(cid)
				token.Attr[i].Val = url
			}
		}

		return bluemonday.HandlerResult{
			Token:         token,
			SkipContent:   false,
			SkipTag:       false,
			DoNotSanitize: false,
		}
	},
)
```

Or blog-posts, editor can form html with special values in custom attributes (e.g. x-my-attribute) and while saving to database, backend can process these attributes while sanitizing without needs to parse html again -> speedup.

I suggest this syntax for custom handlers, it receives html.Token and returns struct with modified token and flags:
* SkipContent - skip content of current html-element only
* SkipTag - skip closing tag for current html-element only
* DoNotSanitize - do not apply sanitizing rules for this html-element only

These flags allows to sanitize with more complex rules that Regexp cannot handle. For example, golang regexp cannot use forward lookup.

**Comment by buro9** [comment]
Let me think on the capability and potential of this.

I am always concerned that as a security package that sanitises HTML we need to be sure that sanitisation is the very last thing that ever happens in a tool chain. I just want to think about whether this continues to keep security first, or whether it prioritises convenience to the detriment of security.

It looks OK at a first glance, but I want to go and think about how the feature could be abused or used by devs not really understanding what they're doing, and whether this could allow them to lower the security the package is supposed to give them.

**Comment by CMogilko** [comment]
If you think that `DoNotSanitize` flag can be misunderstood and used wrong, it can be removed and then ordinary sanitisation will always happens. But I think that it can be useful.

**Comment by buro9** [comment]
Oh it's not that.

Currently bluemonday is a black box, to sanitise code you do not have to know how it works and providing you have a good policy (like the UGCPolicy shipped) and do not allow the `style` attribute then it is secure by default.

The two things I'm concerned about:
1. That devs could use access to the internals to create transformations that create HTML that allows XSS through without them realising they've done this.
2. That access to the internals will prevent us from considering other ways of implementating this in future

The first is a security concern and is the highest priority for me, but the second is also important as I've been considering moving the internals to a balanced tree approach as one of the things with UGC and untrusted HTML is that it can be badly formatted. Using a balanced tree we would fix the most gregarious issues (perhaps not resulting in perfectly valid HTML in the worst cases as we wouldn't be checking that block tags are nested correctly and valid in content, but at least well-formed HTML).

So far... none of the interfaces allow a bad dev to do bad things, or prevents us from considering different approaches that would resolve other issues people have with bad formatted input.

Hence... I'm hesitant.

**Comment by CMogilko** [comment]
1. If `DoNotSanitize` is false, then nothing changes, if XSS is forbidden through policy, it will be sanitized. This case custom handler is pre-sanitisation html-transformation.
2. If you do not plan to change html-parser, it will be ok since `html.Token` is basic internal struct without methods. Otherwise, it can be wrapped with something similar. HTML element always has name and list of attributes (key-value string pairs) by HTML definition.

**Comment by CMogilko** [comment]
I realized that to hide html.Token internal will be good in most cases and so I made minimalistic type similar to html.Token. I think it is enough abstract and most of implementations can be converted to it.

Now custom handler looks like:
```go
p.SetCustomElementHandler(
    func(element bluemonday.Element) bluemonday.HandlerResult {
        for i := range element.Attr {
            // possible image locations
            if element.Attr[i].Key == "src" || element.Attr[i].Key == "background" {
                cid := element.Attr[i].Val // get content-id
                url := GetUrlFromCid(cid)
                element.Attr[i].Val = url
            }
        }

        return bluemonday.HandlerResult{
            Element:       element,
            SkipContent:   false,
            SkipTag:       false,
            DoNotSanitize: false,
        }
    },
)
```

**Comment by CMogilko** [comment]
What about this? Do you need more time to think?

**Comment by CMogilko** [comment]
Hello, is there something new about this?

**Comment by buro9** [comment]
I'm not going to add this. You're free to fork and add, but I still regard it as dangerous and dislike the idea of a DSL or proxy struct to implement this.
