### ISSUE TITLE
apostrophes get turned into HTML entities - &#39;

### ISSUE THREAD

**Issue by Michael77** [microcosm-cc/bluemonday#28]
Is there any way to disable this behavior, or is this a bug?

**Comment by buro9** [comment]
Within the content? That is standard behaviour as part of the Go golang.org/x/net/html package and Go's handling of HTML in general. There is no way to disable that.

It isn't unique to Go, the apostrophe is used to delimit properties on HTML tags and in other places within HTML it is supposed to be escaped. Browsers have been tolerant where we don't escape them, but the Go HTML package escapes them correctly.

Bear in mind HTML is meant to be read by browsers and not humans. This package is to sanitise text that is displayed by browsers. If you are displaying text as plain/text then this package may not be for you as nothing it is doing is necessary for plain/text as the browser is the attack surface that we are protecting. If it's HTML you want to clean, then part of that is converting HTML entities which cannot be disabled.

**Comment by Michael77** [comment]
I didn't realize this was default behavior of the go spec. Thanks for clearing it up!
