### ISSUE TITLE
rel="noopener" should be added if target="_blank" is on a link

### ISSUE THREAD

**Issue by buro9** [microcosm-cc/bluemonday#35]
Background:
https://dev.to/ben/the-targetblank-vulnerability-by-example
https://lists.w3.org/Archives/Public/public-whatwg-archive/2015Jan/0002.html

If `rel="noopener"` is not present on a link that has `target="_blank"` then we should add it.

We already have an option to force adding `target="_blank"` via `AddTargetBlankToFullyQualifiedLinks` and should extend the functionality of that option to add the `rel="noopener"` to mitigate the risk of this attack.

**Comment by shurcooL** [comment]
It is so cool that `bluemonday` can help resolve this issue so effortlessly on a wide scale for all its users.

The background link is very helpful at explaining the issue, thanks for providing it.

**Comment by VojtechVitek** [comment]
Thanks for the fix. Some more links:

- https://mathiasbynens.github.io/rel-noopener/
- https://html.spec.whatwg.org/multipage/semantics.html#link-type-noopener
