### ISSUE TITLE
"javascript" in sanitize.go.

### ISSUE THREAD

**Issue by jckdrpr** [microcosm-cc/bluemonday#37]
Hi I was using bluemonday lib and in the sanitize method I noticed you are expecting the tagname to be "javascript" and not "script". I was unable to understand why that was?

For my case I thought of changing it to "script" but after I do that I get some failing test cases.
```shell
--- FAIL: TestAntiSamy (0.00s)
    sanitize_test.go:769: test 59 failed;
        input   : <SCRIPT>document.write("<SCRI");</SCRIPT>PT SRC="http://ha.ckers.org/xss.js"></SCRIPT>
        output  : PT SRC="http://ha.ckers.org/xss.js">
        expected: PT SRC=&#34;http://ha.ckers.org/xss.js&#34;&gt;
=== RUN   TestXSS
--- FAIL: TestXSS (0.00s)
    sanitize_test.go:1138: test 2 failed;
        input   : <SCRIPT>document.write("<SCRI");</SCRIPT>PT SRC="http://ha.ckers.org/xss.js"></SCRIPT>
        output  : PT SRC="http://ha.ckers.org/xss.js">
        expected: PT SRC=&#34;http://ha.ckers.org/xss.js&#34;&gt;
    sanitize_test.go:1138: test 73 failed;
        input   : <IMG """><SCRIPT>alert("XSS")</SCRIPT>">
        output  : ">
        expected: &#34;&gt;
```

Which should not happen as far as I understand. Can you help me understand this behaviour? And if required investigate it further?

I apologise if it's something obvious that I have missed here.

**Comment by buro9** [comment]
Was that the initial input that you were trying?

And the code does not expect a tagname of script, what are you trying to achieve?

**Comment by jckdrpr** [comment]
I thought the `strings.toLower(mostRecentlyStartedToken)` returns a valid html tag. and expected that if it is indeed a tag that contains javascript the tag should be named `script` rather than `javascript`.

```
		case html.TextToken:

			if !skipElementContent {
				switch strings.ToLower(mostRecentlyStartedToken) {
				case "javascript": // shouldn't it be "script"
					// not encouraged, but if a policy allows JavaScript we
					// should not HTML escape it as that would break the output
					buff.WriteString(token.Data)
				case "style":
					// not encouraged, but if a policy allows CSS styles we
					// should not HTML escape it as that would break the output
					buff.WriteString(token.Data)
				default:
					// HTML escape the text
					buff.WriteString(token.String())
				}
			}
```

**Comment by buro9** [comment]
Nice spot. I'll do some testing.

**Comment by buro9** [comment]
PR https://github.com/microcosm-cc/bluemonday/pull/38 merged, which resolves this bug without changing any tests.
