### ISSUE TITLE
README says supported versions 1.1–1.9, but .travis.yml tests 1.1–1.11

### ISSUE THREAD

**Issue by dmitshur** [microcosm-cc/bluemonday#80]
Compare:

https://github.com/microcosm-cc/bluemonday/blob/506f3da9b7c86d737e91f16b7431df8635871552/README.md#L59-L63

https://github.com/microcosm-cc/bluemonday/blob/506f3da9b7c86d737e91f16b7431df8635871552/.travis.yml#L3-L13

Also, Go 1.12 is out now. Is it supported?

**Comment by buro9** [comment]
Go 1.12 is supported and works fine (am running it).
However there is a change of behaviour that I'm investigating with data URIs which is triggering a single test failure in Go 1.12.

**Comment by buro9** [comment]
Found the data URI issue... it was the test that was wrong. The test data URI contain line breaks which is invalid, and net/url in Go1.12 now rejects invalid URIs that contain line breaks including data URIs. Making the test do the right thing made everything happy for Go1.12.

**Comment by dmitshur** [comment]
Thanks!

**Comment by buro9** [comment]
And now Go1.1 fails on me :roll_eyes: 
https://travis-ci.org/microcosm-cc/bluemonday/builds/506418076

I may just remove this :laughing:

**Comment by buro9** [comment]
Yeah... removed.
