### ISSUE TITLE
How to allow emojis? 

### ISSUE THREAD

**Issue by k0fi** [microcosm-cc/bluemonday#82]
Using sanitization rule below converts emojies like 😀 to `?` :

```
func StripHtml(s string) string {
	p := bluemonday.UGCPolicy()
	p.AllowAttrs("class").OnElements("img")
	return p.Sanitize(s)
}
```

I'm wondering how can I allow emojis to be saved without lowering the sanitization bar too much?

**Comment by k0fi** [comment]
It turned out that the snippet above  just works fine to accept emojis. 
My problem was in mysql database. When I changed the column's collation to utf8mb4_bin, the problem is gone. 
Sorry, please close the issue.

**Comment by buro9** [comment]
Sounds good to me :)

And yes, database collation is a gotcha, as-is passing the output of this through another language and not ensuring that UTF is the charset, etc.
