### ISSUE TITLE
Add functionality to set rel="noreferrer" on a,area,link

### ISSUE THREAD

**Issue by StevenGutzwiller** [microcosm-cc/bluemonday#85]
Right now we have the capability to set rel="nofollow", and we add rel="noopener" if target="_blank". Another potential useful piece of functionality would be to add rel="noreferrer" if the user makes that part of the policy.

I would be willing to write the functionality. I was thinking of the API consisting of two functions:
(p *Policy) RequireNoReferrerOnLinks() *policy
(p *Policy) RequireNoReferrerOnFullyQualifiedLinks() *policy

**Comment by buro9** [comment]
Seems eminently reasonable :) I'd merge it.

**Comment by StevenGutzwiller** [comment]
#86

**Comment by buro9** [comment]
Thanks for the PR :pray:
