### ISSUE TITLE
How to allow custom elements using a regex

### ISSUE THREAD

**Issue by shaydoc** [microcosm-cc/bluemonday#91]
I need to be able to whitelist elements based up a regex pattern
The reason for this is because I have lots of web components.
E.g.  {namespace}-my-element

I would like to white list anything containing  `{namespace}` pattern

Can this be achieved easily?

**Comment by buro9** [comment]
This is a good requirement. Do you have examples of the HTML input and what you'd like the output to be.

**Comment by shaydoc** [comment]
Sure,
  All I want to be able to do is

  ```
   p.AllowElements(regexp.MustCompile(`my-namepsace-*`))
```

So Data In

```
  <div>
      <my-namespace-demo-one />
       <my-namespace-demo-two />
       <not-my-namespace-demo-one />
  </div>
```

Data Out

```
  <div>
      <my-namespace-demo-one />
       <my-namespace-demo-two /> 
  </div>
```

**Comment by shaydoc** [comment]
what ya think @buro9 , would this be an easy update to make?

**Comment by theflyingcodr** [comment]
I'm working on this one at the moment, hope to have a PR up today for :eyes: and feedback

**Comment by theflyingcodr** [comment]
Little bit later than I'd have liked due to other commitments, but PR is now in for this https://github.com/microcosm-cc/bluemonday/pull/92

**Comment by shaydoc** [comment]
be good to get this merged @buro9
